select
	CAST(ORDER_ID AS INT) AS ORDER_ID,
	CAST(CUSTOMER_ID AS INT) AS CUSTOMER_ID,
	CAST(PRODUCT_ID AS INT) AS PRODUCT_ID,
	CAST(QUANTITY AS INT) AS QUANTITY,
	CAST(ORDER_DATE AS DATE) AS ORDER_DATE ,
	STATUS

 from {{source ('tutorial_source','RAW_ORDERS')}}