select 
	CAST(CUSTOMER_ID AS INT) AS CUSTOMER_ID,
	FIRST_NAME,
	LAST_NAME ,
	EMAIL,
	CITY,
	COUNTRY,
	CAST(CREATED_AT AS DATE) AS CREATED_AT
from {{source ('tutorial_source','RAW_CUSTOMERS')}}